### ISSUE TITLE
Consider hiding the cursor

### ISSUE THREAD

**Issue by battaglr** [mrflix/dimensions#16]
I have been using this —amazing extension— for a couple of days, but the constant change of cursor type it's kinda annoying, particularly when measuring wireframes/mockups/comps, since usually you end up with a big zoom cursor.

My suggestion is to remove it entirely, since the current axis are the most precise "cursor" you can get. In case that doesn't cut it, maybe using the crosshair cursor could do the job.

**Comment by mrflix** [comment]
Added in version 2 - live now.
