### ISSUE TITLE
Values updated in inspector

### ISSUE THREAD

**Issue by bjorkblom** [mrflix/dimensions#17]
The dimensions are wrong if the values (properties) have changed after dimensions plugin is activated. Possible solutions would be to activate the plugin by holding down CTRL (like Photoshop CC) and deactivate it by releasing CTRL.

**Comment by mrflix** [comment]
Hey @bjorkblom, good observation. This is still a limitation of Dimensions - check this issue: #24. Ideally dimensions should just keep in sync with property changes. I'm working on this.
