### ISSUE TITLE
Crash after refresh

### ISSUE THREAD

**Issue by aipt32** [mrflix/dimensions#27]
When I run the plugin and then refresh the page it seams to crash and can't be started anymore. I have to restart the browser or disable and reenable it in the Chrome settings.

**Comment by mrflix** [comment]
Hey Simon danke fürs melden! I fixed and updated the extension in the chrome webstore. The update will roll out over the next day or so. You can [force chrome](http://www.howtogeek.com/64525/how-to-manually-force-google-chrome-to-update-extensions/) to update the extension.
