### ISSUE TITLE
Refreshing when active

### ISSUE THREAD

**Issue by nblackburn** [mrflix/dimensions#28]
When the extension is active and the page is reloaded, the plugin fails to work upon activation.

**Comment by mrflix** [comment]
Hey Nathaniel! Thanks for the hint! I found the bug and updated the extension. It can take up to a day until Chrome auto-updates the extension. You can force it by reinstalling the extension. Thanks again!

**Comment by nblackburn** [comment]
My pleasure, great extension by the way.

**Comment by mrflix** [comment]
Thanks!
