### ISSUE TITLE
Add a contrast tolerance in options

### ISSUE THREAD

**Issue by dreame4** [mrflix/dimensions#3]
It would be nice to have an option to increase/decrease contrast tolerance as for some cases you can get quite strange results. I attached an example where the width is calculate incorrectly. 
![screen shot 2014-09-11 at 13 17 44](https://cloud.githubusercontent.com/assets/277870/4233061/c1adbbc4-39a5-11e4-9d61-96a3a46d2f76.png)

**Comment by nblackburn** [comment]
See #20 for potential solution.

**Comment by mrflix** [comment]
I think the initial problem with ghost borders is linked to #24
