### ISSUE TITLE
`direction: rtl` makes dimensions not display properly

### ISSUE THREAD

**Issue by guywald1** [mrflix/dimensions#30]
When using _dimensions_ in an element with a `direction` set to `rtl`, this is what displays:

![image](https://cloud.githubusercontent.com/assets/6546430/19626787/1423ce00-9941-11e6-8e60-e3186697afa9.png)

**Comment by mrflix** [comment]
A very special case. Thanks for reporting it. Please report back if it works. The extension will update itself to 2.0.5 in the next days. You can force the update in the extension list when you activate the developer mode and then press the update extensions button.

**Comment by guywald1** [comment]
@mrflix It does indeed work, nicely handled.
