### ISSUE TITLE
Can provide Firefox browser similar solutions?

### ISSUE THREAD

**Issue by pushring0** [mrflix/dimensions#31]
Hello,I hope to use this extension in Firefox, what should i do?Thanks.

**Comment by mrflix** [comment]
It's in review status on addons.mozilla.org 🙂

**Comment by pushring0** [comment]
@mrflix Thanks,When it appears in the application store, I will close this issues.**Merry Christmas**

**Comment by Mottie** [comment]
The queue for extension review is very long right now... if you give them a little nudge, [like this](https://discourse.mozilla-community.org/t/extremely-long-queue-for-review/13197/2), they might bump you.

**Comment by mrflix** [comment]
FYI: I re-submitted the extension. It was declined because of a missing description text.

**Comment by mrflix** [comment]
Oh wow - the extension was just approved. Only ten minutes after submitting it:
https://addons.mozilla.org/en-US/firefox/addon/dimensions_extension/

Known issues:
  - the shortcut ALT+D doesn't work out of the box. I also didn't find a way to turn it on manually.
