### ISSUE TITLE
Issues when measuring on Mac Retina screen

### ISSUE THREAD

**Issue by jibbajabba** [mrflix/dimensions#8]
I'm seeing some inconsistencies in what Dimensions wants to measure in retina vs. non-retina screens. In the non-retina screen, it has no problem selecting the border of this element, but in the retina screen, it extends beyond it.

![dimensions retina](https://cloud.githubusercontent.com/assets/117222/4239245/7c190ff2-39df-11e4-8dcc-a5389de13c39.png)

**Comment by mrflix** [comment]
Added in version 2 - live now.
